### ISSUE TITLE
Dna Issue

### ISSUE THREAD

**Issue by craigy109** [vincent15k/Toontown-Crystal-Master#1]
## Bugs ##

[ ] - Fix Public Private
[ ] - Fix Gardens
[ ] - Fix Invasion Command
[ ] - Fix Field Office bug, when more that two are in.

## Features ##
[ ] - Add new Pick-A-Toon Screen
[ ] - Make DNA for new DDL street
[ ] - Made DNA for new playground
[ ] - Add Mod Panel

**Comment by vincent15k** [comment]
It is fixed now.
