### ISSUE TITLE
Estate : Catalog

### ISSUE THREAD

**Issue by craigy109** [vincent15k/Toontown-Crystal-Master#18]
Another error is if you use the catalog, hang up the phone and then try to use the catalog again you are unable to, the collision to enable you to load up the catalog seems to be disabled until you go out of your house and back in again.

**Comment by mastervolty** [comment]
Too bad this was fixed in the real source

**Comment by craigy109** [comment]
@mastervolty what do you mean? please

**Comment by craigy109** [comment]
https://github.com/vincent15k/Toontown-Crystal-Master/commit/b332f8cc9bf88e62d31bff36cb8704cfc5505e9f
This issue has now been fixed the collision sphere has been moved and the scale of the phone is slightly bigger
