### ISSUE TITLE
Big Error on Loading Ai And UberDog

### ISSUE THREAD

**Issue by craigy109** [vincent15k/Toontown-Crystal-Master#20]
Sometimes on boot of the server These errors appear

http://pastebin.com/Xf8tdY2B
http://pastebin.com/yuRQCZhU

**Comment by craigy109** [comment]
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

cant boot up at all now even after re cloning

**Comment by vincent15k** [comment]
Oof. Ok. I'll look into this.

**Comment by craigy109** [comment]
do you have a way of been contacted btw ?

**Comment by vincent15k** [comment]
@craigy109 yes, my skype is vincent15k

**Comment by craigy109** [comment]
okay

**Comment by vincent15k** [comment]
Thanks @craigy109 for fixing this!

**Comment by craigy109** [comment]
https://github.com/vincent15k/Toontown-Crystal-Master/commit/e6ab539225be631fc46af3460a8d6fb26f9aa21e
Fixes This For Now
